server:
  port: 8080
spring:
  cloud:
    stream:
      bindings:
        receiveNewOrder-in-0:
          destination: new-order
      kafka:
        binder:
          brokers: localhost:29092,localhost:39092
