server:
  port: 8080
spring:
  cloud:
    stream:
      bindings:
        newOrder-out-0:
          destination: new-order
      kafka:
        binder:
          brokers: localhost:29092,localhost:39092

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
