server:
  port: 8080
spring:
  cloud:
    stream:
      bindings:
        parse-in-0:
          destination: member-in
        parse-out-0:
          destination: member-out
      kafka:
        binder:
          brokers: localhost:29092,localhost:39092
